#!/bin/bash

for i in `podman ps -a --format "{{.Names}}"`; do

	host=`echo $i | cut -f2- -d_ | rev | cut -f2- -d_ |rev`

	if [[ "$host" != "" ]];then
		hosts="$hosts\"$host\","
		alias="$alias\"$host\":{\"ansible_host\":\"$i\"},"
	fi
done

while read -r variable;do

	if [[ "$variable" != "---" ]];then
		key=`echo $variable | cut -f1 -d: | sed 's/\"//g'`
		value=`echo $variable | cut -f2- -d: | sed 's/\"//g' | sed 's/^ *//g'`
		variables="$variables\"$key\":\"$value\","

	fi

done < vars.yml

hosts=${hosts::-1}
alias=${alias::-1}
variables=${variables::-1}

if [ "$1" == "--list" ]; then
cat<<EOF
{
  "bash_hosts": {
    "hosts": [
      "localhost",$hosts
    ],
    "vars": {
      "ansible_connection": "containers.podman.podman",$variables
    }
  },
  "_meta": {
    "hostvars": {
	"localhost":{"ansible_connection":"local"},$alias
    }
  }
}
EOF
elif [ "$1" == "--host" ]; then
  echo '{"_meta": {hostvars": {}}}'
else
  echo "{ }"
fi
